# Generated by Django 4.2.11 on 2024-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appbib', '0003_alter_book_options_remove_book_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic')], max_length=100),
        ),
    ]
