# Generated by Django 4.2.11 on 2024-05-06 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appbib', '0004_alter_book_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non-fiction', 'Non-Fiction'), ('mystery', 'Mystery'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('history', 'History'), ('science', 'Science'), ('romance', 'Romance'), ('horror', 'Horror'), ('adventure', 'Adventure')], max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('AR', 'Arabic'), ('ES', 'Spanish'), ('DE', 'German'), ('IT', 'Italian'), ('RU', 'Russian'), ('JA', 'Japanese')], max_length=100),
        ),
        migrations.CreateModel(
            name='BorrowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_history', to='appbib.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_borrowed'],
            },
        ),
    ]
