# Generated by Django 5.0.4 on 2024-05-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_orderitem_price_remove_orderitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caractéristiques',
            new_name='features',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Drâa-Tafilalet', 'Drâa-Tafilalet'), ('Fès-Meknès', 'Fès-Meknès'), ('Béni Mellal-Khénifra', 'Béni Mellal-Khénifra'), ('Casablanca-Settat', 'Casablanca-Settat'), ('Dakhla-Oued Ed-Dahab', 'Dakhla-Oued Ed-Dahab'), ('Guelmim-Oued Noun', 'Guelmim-Oued Noun'), ('Laâyoune-Sakia alHamra', 'Laâyoune-Sakia alHamra'), ('orientale', 'orientale'), ('Marrakech-Safi', 'Marrakech-Safi'), ('Rabat-Salé-Kénitra', 'Rabat-Salé-Kénitra'), ('Souss-Massa', 'Souss-Massa'), ('Tanger-Tétouan-Al Hoceima', 'Tanger-Tétouan-Al Hoceima')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('AD', 'art'), ('LP', 'santé'), ('GM', 'informatique'), ('TP', 'economie'), ('TV', 'entreprise'), ('TB', 'enfants'), ('SH', 'Science'), ('FC', 'alimentation'), ('ED', 'éducation'), ('SP', 'sport'), ('MU', 'musique')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
